### PR TITLE
Exposes Hosted Zone ID for the bastion ELB.

### PR DESCRIPTION
**Pull request by vladlosev**
@sesas @gimballock This is necessary for the client to create meaningful alias record for the bastion DNS name.

### CODE REVIEW

**Comment by patrickmcclory** [comment]
Error in build... 
SyntaxError: ('invalid syntax', ('/var/cache/drone/src/github.com/DualSpark/cloudformation-environmentbase/.eggs/linecache2-1.0.0-py2.7.egg/linecache2/tests/inspect_fodder2.py', 102, 25, 'def keyworded(*arg1, arg2=1):\n'))

**Comment by vladlosev** [comment]
The CI build now passes - PTAL.

**Comment by gimballock** [comment]
These build issues were independently fixed, and the bastion output has also been added.  Tagged at 0.7.3.

**Comment by vladlosev** [comment]
Oh, nice to hear!

**Pull request closed without merging**
